### ISSUE TITLE
Memory leak of strings returned by linenoise library

### ISSUE THREAD

**Issue by dirkfeytons** [hoelzro/lua-linenoise#10]
I was going through the code and I think you have a memory leak.
In `l_linenoise()` you're invoking the `linenoise()` function from the library. The string that is returned needs to be freed by the caller but this is not done after having pushed it to Lua using `lua_pushstring()`.

**Comment by hoelzro** [comment]
nice catch! I'll push out a fix for this later today.

**Comment by hoelzro** [comment]
@dirkfeytons Thanks again; I've pushed a fix and have rolled out a new LuaRock.

**Comment by dirkfeytons** [comment]
@hoelzro: Thanks! It would be even better if we could get a direct pointer to the linenoise buffer and push that to Lua. That would avoid the `malloc()/free()` for each line.

**Comment by hoelzro** [comment]
@dirkfeytons The only interface that linenoise exposes for actually getting a line is `linenoise` itself; unless @antirez adds a function to allow what you're asking, I'm afraid that's not going to be possible.

**Comment by dirkfeytons** [comment]
Yeah, I know. It was just a suggestion :)
I might patch it in locally here.
