### ISSUE TITLE
Non-printing characters mess up tab completion

### ISSUE THREAD

**Issue by aleclarson** [hoelzro/lua-linenoise#15]
I want to use ANSI coloring on my prompt string, but tab completion is broken by it.

Can this be fixed in this library, or should I create an issue in the C repo?

**Comment by hoelzro** [comment]
Thanks for the report! This will need to need to be handled up the upstream - once it is I can grab the code and integrated it into this library.

**Comment by Sonophoto** [comment]
Guys let me point out this discussion to save some time.  https://github.com/antirez/linenoise/issues/25

**Comment by aleclarson** [comment]
@Sonophoto Thanks, Brig! 👍

@hoelzro The best option right now is to use https://github.com/yhirose/linenoise/tree/utf8-support instead. I'll gladly send a pull request over if you agree.

**Comment by hoelzro** [comment]
@Sonophoto Thanks for the link, but I don't think this is related to multi-byte support.  This is about using ANSI colors for the prompt and linenoise improperly calculating the prompt length.

**Comment by aleclarson** [comment]
@hoelzro Don't speak too soon! ;) #18 fixes this issue. :D
