### ISSUE TITLE
Multi-line support

### ISSUE THREAD

**Issue by aleclarson** [hoelzro/lua-linenoise#17]
See here: https://github.com/antirez/linenoise#single-line-vs-multi-line-editing

**Comment by aleclarson** [comment]
I'm not sure how to test this out. Am I supposed to keep my own local state of whether multiline is enabled, and then loop `L.linenoise` until a key binding of my choice?

By default, it seems there's no designated key binding for exiting multiline mode.

https://github.com/hoelzro/lua-linenoise/blob/master/linenoiselib.c#L977-L981

**Comment by hoelzro** [comment]
I'm not really sure - I haven't used multiline mode.  What did you have in mind that multiline would be used for?

**Comment by aleclarson** [comment]
I'm working it into https://github.com/slembcke/debugger.lua

I figured it out, though!
