### ISSUE TITLE
Cursor position and line editing don't work with UTF-8

### ISSUE THREAD

**Issue by hoelzro** [hoelzro/lua-linenoise#19]
See https://asciinema.org/a/cQA6hlx41uHuFI6AENzMlGv6v for recording of what happens when I try to write "привет"

@aleclarson Would you be able to take a look at this?

**Comment by hoelzro** [comment]
Looking at the example that comes with the utf8-support branch of https://github.com/yhirose/linenoise, it looks like I need to explicitly enable UTF-8 using `linenoiseSetEncodingFunctions`.

**Comment by aleclarson** [comment]
Whoops! Looks like we'll need to include https://github.com/yhirose/linenoise/tree/utf8-support/encodings as well.

https://github.com/yhirose/linenoise/blob/utf8-support/example.c#L59-L62
