### ISSUE TITLE
Keystroke capture

### ISSUE THREAD

**Issue by aleclarson** [hoelzro/lua-linenoise#20]
Some way to capture keystrokes while the prompt is active would be awesome!

**Comment by aleclarson** [comment]
Perhaps `linenoiseRaw` can be used for this? https://github.com/hoelzro/lua-linenoise/blob/master/linenoiselib.c#L1193

**Comment by hoelzro** [comment]
@aleclarson What kind of things did you have in mind for this feature?  It seems a little outside of the scope of this module to me!

**Comment by aleclarson** [comment]
It would be nice for `lua-linenoise` to have it, because then users of https://github.com/slembcke/debugger.lua only need to install `lua-linenoise` to get multiline mode, assuming keystroke capture is used to enter/leave multiline mode.

**Comment by hoelzro** [comment]
Ok, I think I need to learn what multiline mode is for before I can make a judgement call on this.

**Comment by hoelzro** [comment]
@aleclarson Could you explain to me what multiline mode does? I turned it on in a test file and didn't see any difference in behavior

**Comment by aleclarson** [comment]
[This snippet](https://github.com/hoelzro/lua-linenoise/blob/master/linenoiselib.c#L977-L981) moves the cursor to the end of the line when the `enter` key is pressed.

[This snippet](https://github.com/hoelzro/lua-linenoise/blob/master/linenoiselib.c#L683-L773) does some black magic that is unexplainable. 😝 But it has something to do with cursor placement and writing the prompt.

**Comment by hoelzro** [comment]
I didn't see a behavior difference when I tried it out - from a blackbox/user perspective, how does the behavior of the line editor change?

**Comment by aleclarson** [comment]
I can't be certain without looking at the differences between `refreshMultiLine` and `refreshSingleLine`. 😕 Have you taken a look at those yet?

**Comment by hoelzro** [comment]
I haven't taken a close look, no - but what I'm wondering is what difference in behavior you see when you use it in debugger.lua.  I figured it had something to do with storing history entries, but doesn't seem to be the case.

**Comment by aleclarson** [comment]
I can't test it without keystroke capture, unfortunately. :)

**Comment by hoelzro** [comment]
So, from what I can see, `linenoiseSetMultiline` tends to be turned on once and not turned off (see `example.c` in the upstream linenoise repo), but I still can't tell how turning it on changes the behavior - I see the logic behind `refreshMultiLine`, but I'm unclear how multiple lines are even entered, since pressing enter causes `linenoise` to return the line and resets the buffer (maybe the experimental multi-line feature was never finished?).

Regarding the more general keystroke capture feature, I'm very wary of adding features to this binding that aren't in upstream linenoise.

**Comment by aleclarson** [comment]
In the context of a debugger, it makes sense to toggle on/off multi-line mode. I don't think their example is trying to emulate that. They're just looking at CLI args and enabling multi-line for the entire session.

You may be right that the feature was never finished. It's strange that it's been documented if that's the case...

I guess I can just fork this library, and add a simple `CTRL_V` switch case to https://github.com/yhirose/linenoise/blob/utf8-support/linenoise.c

**Comment by hoelzro** [comment]
If you're dead-set on adding a CTRL-V switch, I think maybe forking (for now, anyway) would be best.  We can always merge later!

**Comment by hoelzro** [comment]
@aleclarson Since I won't be adding custom keybindings to lua-linenoise, I'm going to close this.
