### ISSUE TITLE
update linenoise

### ISSUE THREAD

**Issue by dodo** [hoelzro/lua-linenoise#9]
Could you please update linenoise to the latest version?
antirez added support for Home & End a while ago and i would like to use it in lua :)

Thanks in advance!

**Comment by hoelzro** [comment]
@dodo Thanks for pointing that out; I'll be sure to do that!  In the meantime, if you want to use a more recent linenoise, you can set `LIBLINENOISE` as specified in the README to link against a newer version of linenoise: https://github.com/hoelzro/lua-linenoise/blob/master/README.md#compilation

**Comment by hoelzro** [comment]
This is updated in the master branch now!

**Comment by dodo** [comment]
thank you very much :)
